# Generated by Django 3.2.13 on 2022-06-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VMid', models.CharField(max_length=35, verbose_name='vmid')),
                ('VMName', models.CharField(max_length=50, verbose_name='vmname')),
                ('ZoneId', models.CharField(max_length=50, verbose_name='zoneid')),
                ('FolderId', models.CharField(max_length=50, verbose_name='folderid')),
                ('CloudId', models.CharField(max_length=50, verbose_name='cloudid')),
            ],
        ),
    ]
