# Generated by Django 3.2.13 on 2022-06-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedresources',
            options={'verbose_name': 'Cached Resource', 'verbose_name_plural': 'Cached Resources'},
        ),
    ]
