# Generated by Django 3.2.13 on 2022-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cachedresources_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CloudId', models.CharField(max_length=48, verbose_name='cloud_id')),
                ('AccountId', models.CharField(max_length=50, verbose_name='account_id')),
                ('KeyId', models.CharField(max_length=50, verbose_name='account_key_id')),
                ('LockBoxId', models.CharField(max_length=50, verbose_name='lockbox_id')),
                ('KMSKeyId', models.CharField(max_length=50, verbose_name='kms_key_id')),
            ],
            options={
                'verbose_name': 'Cached Resource',
                'verbose_name_plural': 'Cached Resources',
            },
        ),
    ]
