# Generated by Django 3.2.13 on 2022-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cloudauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedresources',
            name='CloudId',
            field=models.CharField(max_length=50, verbose_name='cloud_id'),
        ),
        migrations.AlterField(
            model_name='cachedresources',
            name='FolderId',
            field=models.CharField(max_length=50, verbose_name='folder_id'),
        ),
        migrations.AlterField(
            model_name='cachedresources',
            name='VMName',
            field=models.CharField(max_length=50, verbose_name='vm_name'),
        ),
        migrations.AlterField(
            model_name='cachedresources',
            name='VMid',
            field=models.CharField(max_length=35, verbose_name='vm_id'),
        ),
        migrations.AlterField(
            model_name='cachedresources',
            name='ZoneId',
            field=models.CharField(max_length=50, verbose_name='zone_id'),
        ),
    ]
