# Generated by Django 3.2.13 on 2022-06-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220624_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudauth',
            old_name='CloudId',
            new_name='cloud_id',
        ),
    ]
