# Generated by Django 3.2.13 on 2022-06-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_cloudid_cloudauth_cloud_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedresources',
            old_name='CloudId',
            new_name='cloud_id',
        ),
        migrations.RenameField(
            model_name='cachedresources',
            old_name='FolderId',
            new_name='folder_id',
        ),
        migrations.RenameField(
            model_name='cachedresources',
            old_name='VMid',
            new_name='vm_id',
        ),
        migrations.RenameField(
            model_name='cachedresources',
            old_name='VMName',
            new_name='vm_name',
        ),
        migrations.RenameField(
            model_name='cachedresources',
            old_name='ZoneId',
            new_name='zone_id',
        ),
        migrations.RenameField(
            model_name='cloudauth',
            old_name='AccountId',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='cloudauth',
            old_name='KeyId',
            new_name='account_key_id',
        ),
        migrations.RenameField(
            model_name='cloudauth',
            old_name='KMSKeyId',
            new_name='kms_key_id',
        ),
        migrations.RenameField(
            model_name='cloudauth',
            old_name='LockBoxId',
            new_name='lockbox_id',
        ),
    ]
