# Generated by Django 3.2.13 on 2022-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220624_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAuthAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=48, verbose_name='cloud_id')),
                ('folder_id', models.CharField(max_length=50, verbose_name='folder_id')),
                ('account_id', models.CharField(max_length=50, verbose_name='account_id')),
                ('account_key_id', models.CharField(max_length=50, verbose_name='account_key_id')),
                ('lockbox_id', models.CharField(max_length=50, verbose_name='lockbox_id')),
                ('kms_key_id', models.CharField(max_length=50, verbose_name='kms_key_id')),
            ],
            options={
                'verbose_name': 'Cached Resource',
                'verbose_name_plural': 'Cached Resources',
            },
        ),
        migrations.DeleteModel(
            name='CloudAuth',
        ),
    ]
